# Generated by Django 6.0 on 2025-12-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_hit',
            field=models.BooleanField(default=False),
        ),
    ]
